name: Cake tvls
on:
  workflow_dispatch:
  schedule:
    - cron: '15,30,45 23 * * *' # At 11:15 / 11:30 / 11:45 PM every day
    - cron: '30,45 0 * * *' # At 0:30 / 0:45 AM every day
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute cakeTvls.py
        run: python cakeTvls.py

      - name: Commit and push changes to bribes repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Stake DAO Automation"
          git add .
          git commit -m "Cake tvls"
          git pull --rebase
          git push origin main
        shell: bash
        if: always()